In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

In [5]:
df = pd.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
#df

In [7]:
df_basic = pd.DataFrame(index = df1.columns, columns=['Min', 'Max', 'Sum', 'Mean', 'Mode'])
df_basic['Min'] = df1.min()
df_basic['Max'] = df1.max()
df_basic['Sum'] = df1.sum()
df_basic['Mean'] = df1.mean()
df_basic['Mode'] = df1.mode().T
df_basic

                    Min   Max        Sum       Mean  Mode
HighBP              0.0   1.0   108829.0   0.429001   0.0
HighChol            0.0   1.0   107591.0   0.424121   0.0
CholCheck           0.0   1.0   244210.0   0.962670   1.0
BMI                12.0  98.0  7200038.0  28.382364  27.0
Smoker              0.0   1.0   112423.0   0.443169   0.0
Stroke              0.0   1.0    10292.0   0.040571   0.0
Diabetes            0.0   2.0    75323.0   0.296921   0.0
PhysActivity        0.0   1.0   191920.0   0.756544   1.0
Fruits              0.0   1.0   160898.0   0.634256   1.0
Veggies             0.0   1.0   205841.0   0.811420   1.0
HvyAlcoholConsump   0.0   1.0    14256.0   0.056197   0.0
AnyHealthcare       0.0   1.0   241263.0   0.951053   1.0
NoDocbcCost         0.0   1.0    21354.0   0.084177   0.0
GenHlth             1.0   5.0   637090.0   2.511392   2.0
MentHlth            0.0  30.0   807913.0   3.184772   0.0
PhysHlth            0.0  30.0  1076131.0   4.242081   0.0
DiffWalk            0.0   1.0    42675.0   0.168224   0.0
Sex                 0.0   1.0   111706.0   0.440342   0.0
Age                 1.0  13.0  2037588.0   8.032119   9.0
Education           1.0   6.0  1281194.0   5.050434   6.0
Income              1.0   8.0  1535747.0   6.053875   8.0

In [8]:
class Data_Generation(object):

    def __init__(self, dataset, size, data_type):
        self.dataset = dataset.copy().reset_index(drop = True)
        self.size = size
        self.data_type = data_type
        self.HighBP_nums = []
        self.HighChol_nums = []
        self.CholCheck_nums = []
        self.Smoker_nums = []
        self.Stroke_nums = []
        self.PhysActivity_nums = []
        self.Fruits_nums = []
        self.Veggies_nums= []
        self.HvyAlcoholConsump_nums = []
        self.AnyHealthcare_nums = []
        self.NoDocbcCost_nums = []
        self.DiffWalk_nums = []
        self.Sex_nums = []
        self.BMI_nums = []
        self.Diabetes_nums = []
        self.GenHlth_nums = []
        self.MentHlth_nums = []
        self.PhysHlth_nums = []
        self.Age_nums = []
        self.Education_nums = []
        self.Income_nums = []
        self.generated_data = []

    def generating_data(self):
        self.HighBP_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HighChol_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.CholCheck_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Smoker_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Stroke_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.PhysActivity_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Fruits_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Veggies_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.HvyAlcoholConsump_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.AnyHealthcare_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.NoDocbcCost_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.DiffWalk_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.Sex_nums = np.random.choice([0, 1], size=self.size).astype(self.data_type)
        self.BMI_nums = np.random.choice(range(12, 99), size=self.size).astype(self.data_type)
        self.Diabetes_nums = np.random.choice(range(0, 3), size = self.size).astype(self.data_type)
        self.GenHlth_nums = np.random.choice(range(1, 6), size = self.size).astype(self.data_type)
        self.MentHlth_nums = np.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.PhysHlth_nums = np.random.choice(range(0, 31), size = self.size).astype(self.data_type)
        self.Age_nums = np.random.choice(range(1, 14), size = self.size).astype(self.data_type)
        self.Education_nums = np.random.choice(range(1, 7), size = self.size).astype(self.data_type)
        self.Income_nums = np.random.choice(range(1, 9), size = self.size).astype(self.data_type)
        
        
    def generating_dataframe(self):
        global generated_data_global

        self.generated_data = pd.DataFrame({"HighBP": self.HighBP_nums, 
                                            'HighChol': self.HighChol_nums,
                                            'CholCheck' : self.CholCheck_nums,
                                            'BMI' : self.BMI_nums, 
                                            'Smoker' : self.Smoker_nums, 
                                            'Stroke' : self.Stroke_nums, 
                                            'Diabetes' : self.Diabetes_nums,
                                            'PhysActivity' : self.PhysActivity_nums, 
                                            'Fruits' : self.Fruits_nums, 
                                            'Veggies' : self.Veggies_nums,
                                            'HvyAlcoholConsump' : self.HvyAlcoholConsump_nums, 
                                            'AnyHealthcare' : self.AnyHealthcare_nums, 
                                            'NoDocbcCost' : self.NoDocbcCost_nums,
                                            'GenHlth' : self.GenHlth_nums, 
                                            'MentHlth' : self.MentHlth_nums, 
                                            'PhysHlth' : self.PhysHlth_nums, 
                                            'DiffWalk' : self.DiffWalk_nums, 
                                            'Sex' : self.Sex_nums, 
                                            'Age' : self.Age_nums, 
                                            'Education' : self.Education_nums,
                                            'Income' : self.Income_nums})

        
        generated_data_global = self.generated_data

    def main(self):
        self.generating_data()
        self.generating_dataframe()

In [9]:
gen_df = Data_Generation(df, 50000000, float)

In [10]:
gen_df.main()

In [11]:
generated_data_global

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,0.0,88.0,1.0,0.0,2.0,0.0,0.0,0.0,...,1.0,1.0,2.0,24.0,23.0,0.0,1.0,8.0,2.0,7.0
1,1.0,1.0,0.0,50.0,1.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,27.0,20.0,0.0,0.0,4.0,2.0,7.0
2,0.0,0.0,1.0,27.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,4.0,18.0,14.0,0.0,1.0,13.0,4.0,7.0
3,0.0,0.0,0.0,75.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,4.0,8.0,2.0,1.0,0.0,13.0,2.0,7.0
4,1.0,0.0,1.0,29.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,2.0,28.0,21.0,0.0,0.0,2.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49999995,0.0,1.0,1.0,79.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1.0,1.0,2.0,27.0,0.0,1.0,1.0,10.0,6.0,2.0
49999996,1.0,1.0,1.0,94.0,0.0,1.0,2.0,0.0,1.0,0.0,...,1.0,0.0,1.0,13.0,25.0,0.0,1.0,13.0,3.0,8.0
49999997,1.0,1.0,0.0,98.0,1.0,0.0,2.0,0.0,0.0,0.0,...,0.0,1.0,3.0,5.0,21.0,1.0,1.0,5.0,5.0,5.0
49999998,1.0,0.0,0.0,20.0,1.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,11.0,14.0,1.0,1.0,2.0,5.0,5.0
49999999,0.0,0.0,0.0,94.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,7.0,20.0,0.0,1.0,2.0,6.0,7.0