In [16]:
import numpy as np
import pandas as pd

In [135]:
df = pd.read_csv('heart_disease_health_indicators_BRFSS2015.csv')
df

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [149]:
class Normalization(object):
    def __init__(self, dataset):
        self.dataset = dataset.reset_index(drop = True)
        self.df_max_scaled = dataset.copy()
        self.df_min_max_scaled = dataset.copy()
        self.z_scaled = dataset.copy()

    def df_basic(self, dataset):
        global df_basic_global
        
        self.df_basic = pd.DataFrame(index = self.dataset.columns, columns=['Min', 'Max', 'Sum', 'Mean', 'Mode'])
        self.df_basic['Min'] = self.dataset.min()
        self.df_basic['Max'] = self.dataset.max()
        self.df_basic['Sum'] = self.dataset.sum()
        self.df_basic['Mean'] = self.dataset.mean()
        self.df_basic['Mode'] = self.dataset.mode().T
        
        df_basic_global = self.df_basic

    def max_scaled(self):
        global df_max_scaled_global

        for column in self.df_max_scaled.columns: 
            self.df_max_scaled[column] = self.df_max_scaled[column] / self.df_max_scaled[column].abs().max()

        df_max_scaled_global = self.df_max_scaled

    def min_max_scaled(self):
        global df_min_max_scaled_global
        
        for column in self.df_min_max_scaled.columns:
            self.df_min_max_scaled[column] = (self.df_min_max_scaled[column] - self.df_min_max_scaled[column].min()) / (self.df_min_max_scaled[column].max()  - self.df_min_max_scaled[column].min())
        df_min_max_scaled_global = self.df_min_max_scaled

    def z_scaled_class(self):
        global z_scaled_global

        for column in self.z_scaled.columns:
            self.z_scaled[column] = (self.z_scaled[column] - self.z_scaled[column].mean()) / self.z_scaled[column].std()

        z_scaled_global = self.z_scaled

    def main(self):
        self.df_basic(self.dataset)
        self.max_scaled()
        self.min_max_scaled()
        self.z_scaled_class()

In [150]:
norm = Normalization(df)

In [151]:
norm.main()

In [152]:
df_basic_global

                       Min   Max        Sum       Mean  Mode
HeartDiseaseorAttack   0.0   1.0    23893.0   0.094186   0.0
HighBP                 0.0   1.0   108829.0   0.429001   0.0
HighChol               0.0   1.0   107591.0   0.424121   0.0
CholCheck              0.0   1.0   244210.0   0.962670   1.0
BMI                   12.0  98.0  7200038.0  28.382364  27.0
Smoker                 0.0   1.0   112423.0   0.443169   0.0
Stroke                 0.0   1.0    10292.0   0.040571   0.0
Diabetes               0.0   2.0    75323.0   0.296921   0.0
PhysActivity           0.0   1.0   191920.0   0.756544   1.0
Fruits                 0.0   1.0   160898.0   0.634256   1.0
Veggies                0.0   1.0   205841.0   0.811420   1.0
HvyAlcoholConsump      0.0   1.0    14256.0   0.056197   0.0
AnyHealthcare          0.0   1.0   241263.0   0.951053   1.0
NoDocbcCost            0.0   1.0    21354.0   0.084177   0.0
GenHlth                1.0   5.0   637090.0   2.511392   2.0
MentHlth               0.0  30.0   807913.0   3.184772   0.0
PhysHlth               0.0  30.0  1076131.0   4.242081   0.0
DiffWalk               0.0   1.0    42675.0   0.168224   0.0
Sex                    0.0   1.0   111706.0   0.440342   0.0
Age                    1.0  13.0  2037588.0   8.032119   9.0
Education              1.0   6.0  1281194.0   5.050434   6.0
Income                 1.0   8.0  1535747.0   6.053875   8.0

In [153]:
df_max_scaled_global

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,0.408163,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.6,0.500000,1.0,0.0,0.692308,0.666667,0.375
1,0.0,0.0,0.0,0.0,0.255102,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.6,0.0,0.000000,0.0,0.0,0.538462,1.000000,0.125
2,0.0,1.0,1.0,1.0,0.285714,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.000000,1.0,0.0,0.692308,0.666667,1.000
3,0.0,1.0,0.0,1.0,0.275510,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.846154,0.500000,0.750
4,0.0,1.0,1.0,1.0,0.244898,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.4,0.1,0.000000,0.0,0.0,0.846154,0.833333,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.459184,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.166667,0.0,1.0,0.384615,1.000000,0.875
253676,0.0,1.0,1.0,1.0,0.183673,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.8,0.0,0.000000,1.0,0.0,0.846154,0.333333,0.500
253677,0.0,0.0,0.0,1.0,0.285714,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.2,0.0,0.000000,0.0,0.0,0.153846,0.833333,0.250
253678,0.0,1.0,0.0,1.0,0.234694,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.6,0.0,0.000000,0.0,1.0,0.538462,0.833333,0.125
253679,1.0,1.0,1.0,1.0,0.255102,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.4,0.0,0.000000,0.0,0.0,0.692308,1.000000,0.250

In [154]:
df_min_max_scaled_global

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,0.325581,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.00,0.6,0.500000,1.0,0.0,0.666667,0.6,0.285714
1,0.0,0.0,0.0,0.0,0.151163,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.50,0.0,0.000000,0.0,0.0,0.500000,1.0,0.000000
2,0.0,1.0,1.0,1.0,0.186047,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,1.00,1.0,1.000000,1.0,0.0,0.666667,0.6,1.000000
3,0.0,1.0,0.0,1.0,0.174419,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.833333,0.4,0.714286
4,0.0,1.0,1.0,1.0,0.139535,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.25,0.1,0.000000,0.0,0.0,0.833333,0.8,0.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.383721,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.166667,0.0,1.0,0.333333,1.0,0.857143
253676,0.0,1.0,1.0,1.0,0.069767,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.75,0.0,0.000000,1.0,0.0,0.833333,0.2,0.428571
253677,0.0,0.0,0.0,1.0,0.186047,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.00,0.0,0.000000,0.0,0.0,0.083333,0.8,0.142857
253678,0.0,1.0,0.0,1.0,0.127907,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.50,0.0,0.000000,0.0,1.0,0.500000,0.8,0.000000
253679,1.0,1.0,1.0,1.0,0.151163,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,0.25,0.0,0.000000,0.0,0.0,0.666667,1.0,0.142857

In [155]:
z_scaled_global

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,-0.322457,1.153686,1.165252,0.196921,1.757932,1.120925,-0.205636,-0.425291,-1.762810,-1.316869,...,0.226862,-0.303173,2.329116,1.998588,1.233996,2.223611,-0.887019,0.316899,-1.065593,-1.474484
1,-0.322457,-0.866784,-0.858180,-5.078154,-0.511805,1.120925,-0.205636,-0.425291,0.567274,-1.316869,...,-4.407945,3.298439,0.457293,-0.429629,-0.486591,-0.449717,-0.887019,-0.337932,0.963270,-2.440133
2,-0.322457,1.153686,1.165252,0.196921,-0.057858,-0.892117,-0.205636,-0.425291,-1.762810,0.759374,...,0.226862,3.298439,2.329116,3.617399,2.954584,2.223611,-0.887019,0.316899,-1.065593,0.939636
3,-0.322457,1.153686,-0.858180,0.196921,-0.209173,-0.892117,-0.205636,-0.425291,0.567274,0.759374,...,0.226862,-0.303173,-0.478618,-0.429629,-0.486591,-0.449717,-0.887019,0.971731,-2.080024,-0.026012
4,-0.322457,1.153686,1.165252,0.196921,-0.663121,-0.892117,-0.205636,-0.425291,0.567274,0.759374,...,0.226862,-0.303173,-0.478618,-0.024926,-0.486591,-0.449717,-0.887019,0.971731,-0.051161,-0.991660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,-0.322457,1.153686,1.165252,0.196921,2.514511,-0.892117,-0.205636,-0.425291,-1.762810,0.759374,...,0.226862,-0.303173,0.457293,-0.429629,0.086938,-0.449717,1.127367,-0.992764,0.963270,0.456812
253676,-0.322457,1.153686,1.165252,0.196921,-1.571016,-0.892117,-0.205636,2.439383,-1.762810,-1.316869,...,0.226862,-0.303173,1.393205,-0.429629,-0.486591,2.223611,-0.887019,0.971731,-3.094455,-0.991660
253677,-0.322457,-0.866784,-0.858180,0.196921,-0.057858,-0.892117,-0.205636,-0.425291,0.567274,0.759374,...,0.226862,-0.303173,-1.414529,-0.429629,-0.486591,-0.449717,-0.887019,-1.975011,-0.051161,-1.957309
253678,-0.322457,1.153686,-0.858180,0.196921,-0.814437,-0.892117,-0.205636,-0.425291,-1.762810,0.759374,...,0.226862,-0.303173,0.457293,-0.429629,-0.486591,-0.449717,1.127367,-0.337932,-0.051161,-2.440133
253679,3.101177,1.153686,1.165252,0.196921,-0.511805,-0.892117,-0.205636,2.439383,0.567274,0.759374,...,0.226862,-0.303173,-0.478618,-0.429629,-0.486591,-0.449717,-0.887019,0.316899,0.963270,-1.957309